import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <ul>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/about-us">About Us</Link>
            </li>
            <li>
              <Link href="/events">Events</Link>
            </li>
          </ul>
        </nav>
      </header>

      <main className={styles.main}>
        {data.map((ev) => {
          return (
            <Link href={`/events/${ev.id}`} key={ev.id}>
              <Image src={ev.image} alt={ev.title} width={200} height={100} />
              <h2>{ev.title}</h2>
              <p>{ev.description}</p>
            </Link>
          );
        })}
      </main>
    </>
  );
}
export async function getServerSideProps(context) {
  const { events_categories } = await import("/data/data.json");
  return {
    props: {
      data: events_categories,
    },
  };
}
